server:
  port: 80
Spring:
  application:
    name: COM.HUASHUIKUN.SERVICE
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #将服务注册到eureka集群中
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/